name: Ежедневный отчет по рекламным кампаниям Facebook

on:
  schedule:
    # Запуск каждый день в 8:00 UTC (это соответствует 11:00 МСК)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Позволяет запускать workflow вручную из интерфейса GitHub

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          
      - name: Create directories
        run: |
          mkdir -p reports
          mkdir -p cache
          mkdir -p logs
          
      - name: Set up environment variables
        run: |
          echo "APP_ID=${{ secrets.FB_APP_ID }}" >> $GITHUB_ENV
          echo "APP_SECRET=${{ secrets.FB_APP_SECRET }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.FB_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "AD_ACCOUNT_ID=${{ secrets.FB_AD_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV
          echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
          echo "CACHE_ENABLED=true" >> $GITHUB_ENV
          echo "CACHE_DIR=./cache" >> $GITHUB_ENV
          echo "REPORTS_DIR=./reports" >> $GITHUB_ENV
          
      - name: Run daily report script
        run: python daily_ad_report.py
        
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: fb-ads-report
          path: reports/
          retention-days: 7 